# Configuration settings for html-proofer.
# For configuration documentation, refer to: https://github.com/gjtorikian/html-proofer#configuration
# For configuration defaults, refer to: https://github.com/gjtorikian/html-proofer/blob/master/lib/html-proofer/configuration.rb
#
html-proofer:

  # Validate HTML
  :check_html: true
  
  # Do not check external links.
  :disable_external: true

  # Report only errors that fall within the 4xx status code range.
  :only_4xx: true

  # Ignores images with empty alt tags.
  :empty_alt_ignore: true
  
  # Sort errors by description in the report
  :error_sort: :desc

  # Use up to 3 parallel processes to speed up internal file checks.
  :parallel:
    :in_processes: 3
  
  :cache:
    :timeframe: 2w

  # Ignore entirely the files which pathname matches a specified pattern 
  :file_ignore:
    - !ruby/regexp /guides\/v2\.3\/mrg/
    - !ruby/regexp /guides\/v2\.4\/mrg/

  :internal_domains:
    - devdocs.magento.com

  # Ignore any link that includes a specified pattern
  :url_ignore:
    - !ruby/regexp /guides\/v2\.2/
    - !ruby/regexp /\/v2\.4\/mrg/
    - !ruby/regexp /\/redoc\/2\.4\//
    - !ruby/regexp /\/download\//
  
