# Site settings
encoding: "utf-8"
title: Magento 2 Developer Documentation
email: mailto:DL-Magento-Doc-Feedback@ebay.com
twitter_url: https://twitter.com/MagentoDevDocs
description: > # this means to ignore newlines until "baseurl:"
  Magento 2 Developer Guide.
baseurl: "/"
description: Magento 2 Developer's Guide
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gdeurl: "/guides/v2.0/"
githuburl: "http://github.com/magento/devdocs/blob/develop/guides/v2.0/"
namem2fedg: "Magento 2 Frontend Developer's Guide"
namem2devgde: "Magento 2 Developer's Guide"
namem2apiref: "Magento 2 API Reference"
namem2install: "Magento 2 Installation Guide"
mage2000url: "https://github.com/magento/magento2/blob/develop/"
# toc_baseurl: "http://devdocs.magento.com"
m1xgdeurl: "/guides/m1x/"
m1xgithuburl: "http://github.com/magento/devdocs/blob/develop/guides/m1x/"

gems:
  - jekyll-redirect-from


# Build settings
markdown: kramdown
highlighter: pygments
