# Site settings
encoding: "utf-8"
title: Magento 2 Developer Documentation
email: mailto:DL-Magento-Doc-Feedback@ebay.com
description: Magento 2 Developer Guide
baseurl: "/"
# url: "https://github.com/magento/devdocs" # the base hostname & protocol for your site
# twitter_username: magento
# github_username:  magento

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gdeurl: "/guides/v2.0/"
githuburl: "https://github.com/magento/devdocs/tree/develop/guides/v2.0/"
namem2fedg: "Magento 2 Frontend Developer's Guide"
namem2devgde: "Magento 2 Developer's Guide"
namem2apiref: "Magento 2 API Reference"
namem2install: "Magento 2 Installation Guide"
mage2000url: "https://github.com/magento/magento2/blob/develop/"
# toc_baseurl: "https://github.corp.ebay.com/pages/Magento/devdocs_internal"
m1xgdeurl: "/guides/m1x/"
m1xgithuburl: "https://github.com/magento/devdocs/tree/develop/guides/m1x/"

# Build settings
markdown: kramdown
highlighter: pygments

