---
title: Magento_InventoryConfigurationApi
source_repo: inventory
release: 1.2.1
github_path: InventoryConfigurationApi/README.md
last_modified_at: '2018-11-09 00:12:40 +0200'
content: |-
  The `InventoryConfigurationApi` module provides service contracts for inventory management configuration.

  This module is part of the new inventory infrastructure. The
  [Inventory Management overview](https://devdocs.magento.com/guides/v2.3/inventory/index.html)
  describes the MSI (Multi-Source Inventory) project in more detail.

  ## Installation details

  This module is installed as part of Magento Open Source. It cannot be disabled.

  ## Extensibility

  The `InventoryConfigurationApi` module contains extension points and APIs that 3rd-party developers
  can use to provide custom inventory functionality.

  ### Public APIs

  Public APIs are defined in the `Api` and `Api/Data` directories.
