---
title: Magento_InventoryConfigurableProductIndexer
source_repo: inventory
release: 1.1.6
github_path: InventoryConfigurableProductIndexer/README.md
last_modified_at: '2018-11-09 00:12:40 +0200'
content: |-
  The `InventoryConfigurableProductIndexer` module integrates inventory management business logic into Magento's indexation logic for configurable products.

  This module is part of the new inventory infrastructure. The
  [Inventory Management overview](https://devdocs.magento.com/guides/v2.3/inventory/index.html)
  describes the MSI (Multi-Source Inventory) project in more detail.

  ## Installation details

  This module is installed as part of Magento Open Source. It cannot be deleted or disabled.

  ## Extension points and service contracts

  There are no extension points or service contracts for this module.
