---
title: Magento_InventoryConfigurableProductAdminUi
source_repo: inventory
release: 1.1.6
github_path: InventoryConfigurableProductAdminUi/README.md
last_modified_at: '2018-11-09 00:12:40 +0200'
content: "The `InventoryConfigurableProductAdminUi`extends the Magento Admin UI to
  add inventory management functionality.\n\nThis module is part of the new inventory
  infrastructure. The\n[Inventory Management overview](https://devdocs.magento.com/guides/v2.3/inventory/index.html)\ndescribes
  the MSI (Multi-Source Inventory) project in more detail.\n\n## Installation details\n\nThis
  module is installed as part of Magento Open Source. It may be disabled if the Inventory
  Management UI\nis provided by a 3rd-party system or if you run a headless version
  of Magento.\n \n## Extensibility\n\nThe `InventoryConfigurableProductAdminUi` module
  contains several extension points.\n\n### UI Components\n\nThe `view/adminhtml/ui_component`
  directory contains extensible UI components."
