---
title: Magento_ConfigurableProduct
source_repo: magento2ce
release: 2.3.6
github_path: app/code/Magento/ConfigurableProduct/README.md
last_modified_at: '2014-12-12 12:14:06 -0800'
content: |-
  Magento_ConfigurableProduct module introduces new product type in the Magento application called Configurable Product.
  This module is designed to extend existing functionality of Magento_Catalog module by adding new product type.

  Configurable Products let the customers select the variant they desire by choosing options.
  For example, store owner sells t-shirts in two colors and three sizes.
