---
title: Magento_ConfigurableSharedCatalog
source_repo: magento2b2b
release: 1.1.6
github_path: app/code/Magento/ConfigurableSharedCatalog/README.md
last_modified_at: '2017-02-15 17:02:23 +0300'
content: "## Overview\n\nThe Magento_ConfigurableSharedCatalog module enables configurable
  products to be added to a shared catalog in an B2B environment. This module extends
  Magento_SharedCatalog and Magento_Configurable modules.\n\nThe Magento_ConfigurableSharedCatalog
  module provides the following features:\n\n* Display base and custom prices for
  configurable products within a shared catalog. There is no ability to edit the price
  of a configurable product.\n\n* Control the visibility of configurable products
  in quotes and orders. Only those configurable products that have been added to a
  shared catalog will be available for searches via the \"Add by SKU\" feature in
  quotes and orders. \n\n \n## Installation details\n \nThe Magento_ConfigurableSharedCatalog
  module has a dependency on the Magento_SharedCatalog and Magento_Configurable modules,
  which must be installed and enabled first. This module does not create any backward
  incompatible changes. It can be uninstalled or deactivated at any time. \n \n##
  Structure\n \n[Learn about a typical file structure for a Magento 2 module](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/module-file-structure.html).\n
  \n## Extensibility\n \nExtension developers can interact with the Magento_ConfigurableSharedCatalog
  module. For more information about the Magento extension mechanism, see [Magento
  plug-ins](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html).\n
  \n[The Magento dependency injection mechanism](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/depend-inj.html)
  enables you to override the functionality of the Magento_ConfigurableSharedCatalog
  module.\n\n### Layouts\n \nYou can extend and override layouts in the `Magento\\ConfigurableSharedCatalog\\view\\adminhtml\\layout`
  directories.\n\nFor more information about layouts, see the [Layout documentation](http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/layout-overview.html).\n
  \n### UI components\n\nThe following directory contains extensible UI components:
  \n\n* `Magento\\ConfigurableSharedCatalog\\view\\adminhtml\\ui_component` - renderer
  for pricing and structure listings\n\nFor more information, see [UI Listing/Grid
  Component](http://devdocs.magento.com/guides/v2.2/ui-components/ui-listing-grid.html).\n\n##
  Additional information\n \nYou can track [backward incompatible changes made in
  a Magento B2b mainline after the Magento 2.2 release](http://devdocs.magento.com/guides/v2.2/release-notes/changes/b2b_changes.html)."
