---
title: Magento_ConfigurableRequisitionList
source_repo: magento2b2b
release: 1.1.6
github_path: app/code/Magento/ConfigurableRequisitionList/README.md
last_modified_at: '2017-04-10 10:33:01 +0300'
content: "## Overview\n\nThe Magento_ConfigurableRequisitionList module enables configurable
  products to be displayed in a requisition list in an B2B environment. This module
  extends Magento_RequisitionList and Magento_Configurable modules.\n\nThe Magento_ConfigurableRequisitionList
  module provides the following features:\n\n* Display configurable products in a
  requisition list.\n\n* Add configurable products to cart from a requisition list.
  \n \n## Installation details\n \nThe Magento_ConfigurableRequisitionList module
  has a dependency on the Magento_RequisitionList and Magento_Configurable modules,
  which must be installed and enabled first. This module does not create any backward
  incompatible changes. It can be uninstalled or deactivated at any time. \n \n##
  Structure\n \n[Learn about a typical file structure for a Magento 2 module](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/module-file-structure.html).\n\n###
  Layouts\n \nYou can extend and override layouts in the `Magento\\ConfigurableRequisitionList\\view\\frontend\\layout`
  directories.\n\nFor more information about layouts, see the [Layout documentation](http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/layout-overview.html).\n\n##
  Additional information\n \nYou can track [backward incompatible changes made in
  a Magento B2b mainline after the Magento 2.2 release](http://devdocs.magento.com/guides/v2.2/release-notes/changes/b2b_changes.html)."
