---
title: Magento_ConfigurableRequisitionList
source_repo: magento2b2b
release: 1.1.7
github_path: app/code/Magento/ConfigurableRequisitionList/README.md
last_modified_at: '2021-04-26 15:17:51 -0500'
content: |-
  ## Overview

  The Magento_ConfigurableRequisitionList module enables configurable products to be displayed in a requisition list in an B2B environment. This module extends Magento_RequisitionList and Magento_Configurable modules.

  The Magento_ConfigurableRequisitionList module provides the following features:

  * Display configurable products in a requisition list.

  * Add configurable products to cart from a requisition list.

  ## Installation details

  The Magento_ConfigurableRequisitionList module has a dependency on the Magento_RequisitionList and Magento_Configurable modules, which must be installed and enabled first. This module does not create any backward incompatible changes. It can be uninstalled or deactivated at any time.

  ## Structure

  [Learn about a typical file structure for a Magento 2 module](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/module-file-structure.html).

  ### Layouts

  You can extend and override layouts in the `Magento\ConfigurableRequisitionList\view\frontend\layout` directories.

  For more information about layouts, see the [Layout documentation](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-overview.html).

  ## Additional information

  You can track [backward incompatible changes made in a Magento B2b mainline after the Magento 2.3 release](https://devdocs.magento.com/guides/v2.3/release-notes/changes/b2b_changes.html).
