---
title: Magento_QuoteConfigurableOptions
source_repo: magento2ce
release: 2.4.1
github_path: app/code/Magento/QuoteConfigurableOptions/README.md
last_modified_at: '2020-05-07 17:17:41 +0200'
content: "**QuoteConfigurableOptions** provides data provider for creating buy request
  for configurable products."
