---
title: InventoryConfigurableProductFrontendUi
release: 2.4.3
content: |-
  The `InventoryConfigurableProductFrontendUi` adds info about salable quantity for configurable variations in product page.

  This module is a part of the new inventory infrastructure. The
  [Inventory Management overview](https://devdocs.magento.com/guides/v2.4/inventory/index.html)
  describes the MSI (Multi-Source Inventory) project in more detail.

  ## Installation details

  This module is installed as part of Magento Open Source. It may be disabled if the Inventory Management UI
  is provided by a 3rd-party system or if you run a headless version of Magento.

  ## Extensibility

  The `InventoryConfigurableProductFrontendUi` module contains several extension points.
