---
title: MsrpConfigurableProduct
content: "The **Magento_MsrpConfigurableProduct** module provides type and resolver
  information for the Magento_Msrp module from the ConfigurableProduct module.\nProvides
  implementation of msrp price calculation for Configurable Product.\n\n## Installation\n\nFor
  information about a module installation in Magento 2, see [Enable or disable modules](https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-enable.html)\n\n##
  Structure\n\n`Pricing\\` - directory contains implementation of msrp price calculation
  \nfor Grouped Product (`Magento\\MsrpGroupedProduct\\Pricing\\MsrpPriceCalculator`
  class). \n\nFor information about a typical file structure of a module in Magento
  2,\n see [Module file structure](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/module-file-structure.html#module-file-structure).\n\n##
  Extensibility\n\n Extension developers can interact with the Magento_Msrp module.
  For more information about the Magento extension mechanism, see [Magento plug-ins](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/plugins.html).\n\n[The
  Magento dependency injection mechanism](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/depend-inj.html)
  enables you to override the functionality of the Magento_Msrp module.\n\n### Layouts\n\nFor
  more information about a layout in Magento 2, see the [Layout documentation](http://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-overview.html).\n\n###
  UI components\n\nFor information about a UI component in Magento 2, see [Overview
  of UI components](http://devdocs.magento.com/guides/v2.3/ui_comp_guide/bk-ui_comps.html).\n\n##
  Additional information\n\nFor information about significant changes in patch releases,
  see [2.4.x Release information](https://devdocs.magento.com/guides/v2.4/release-notes/bk-release-notes.html)."
