---
title: ConfigurableNegotiableQuote
content: |-
  The Magento_ConfigurableNegotiableQuote module enables configurable products to be displayed in a negotiable quote in an B2B environment. This module extends Magento_NegotiableQuote and Magento_Configurable modules.

  The Magento_ConfigurableNegotiableQuote module provides the following features:

  * Display configurable products in a negotiable quote.

  * Order configurable products from a negotiable quote.

  ## Installation details

  The Magento_ConfigurableNegotiableQuote module has a dependency on the Magento_NegotiableQuote and Magento_Configurable modules, which must be installed and enabled first. This module does not create any backward incompatible changes. It can be uninstalled or deactivated at any time.

  ## Structure

  [Learn about a typical file structure for a Magento 2 module](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/module-file-structure.html).

  ## Extensibility

  Extension developers can interact with the Magento_ConfigurableNegotiableQuote module. For more information about the Magento extension mechanism, see [Magento plug-ins](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/plugins.html).

  [The Magento dependency injection mechanism](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/depend-inj.html) enables you to override the functionality of the Magento_ConfigurableNegotiableQuote module.
