---
title: Magento_ConfigurableNegotiableQuote
source_repo: magento2b2b
release: 1.3.0
github_path: app/code/Magento/ConfigurableNegotiableQuote/README.md
last_modified_at: '2017-04-10 10:33:01 +0300'
content: "## Overview\n\nThe Magento_ConfigurableNegotiableQuote module enables configurable
  products to be displayed in a negotiable quote in an B2B environment. This module
  extends Magento_NegotiableQuote and Magento_Configurable modules.\n\nThe Magento_ConfigurableNegotiableQuote
  module provides the following features:\n\n* Display configurable products in a
  negotiable quote.\n \n* Order configurable products from a negotiable quote.\n \n##
  Installation details\n \nThe Magento_ConfigurableNegotiableQuote module has a dependency
  on the Magento_NegotiableQuote and Magento_Configurable modules, which must be installed
  and enabled first. This module does not create any backward incompatible changes.
  It can be uninstalled or deactivated at any time. \n \n## Structure\n \n[Learn about
  a typical file structure for a Magento 2 module](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/module-file-structure.html).\n
  \n## Extensibility\n \nExtension developers can interact with the Magento_ConfigurableNegotiableQuote
  module. For more information about the Magento extension mechanism, see [Magento
  plug-ins](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html).\n
  \n[The Magento dependency injection mechanism](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/depend-inj.html)
  enables you to override the functionality of the Magento_ConfigurableNegotiableQuote
  module.\n\n## Additional information\n \nYou can track [backward incompatible changes
  made in a Magento B2b mainline after the Magento 2.2 release](http://devdocs.magento.com/guides/v2.2/release-notes/changes/b2b_changes.html)."
