---
title: Magento_SwaggerWebapi
edition: ce
content: The Magento_SwaggerWebapi module provides the implementation of the REST
  Webapi module with Magento_Swagger.
last_modified_at: '2018-03-23 17:48:45 +1300'
